thephpleague/fractal

pagination.md
The `addQuery` method can be found on `Illuminate\Pagination\Paginator` rather than on `League\Fractal\Pagination\IlluminatePaginatorAdapter` as originally suggested in the example.
=> Correction to pagination query parameters example in documentation

src/Resource/Collection.php
These methods are defined in the `ResourceAbstract` class and do not need to be overloaded.
=> Repetitive overloaded methods

src/TransformerAbstract.php
This PR fixes #157.
This PR changes the accessing of the default and available includes to use the getter methods, instead of direct property access. More details as to why this change was made or why it may be important can be found in #157.
=> Access includes via getter methods

src/Scope.php, src/Serializer/SerializerAbstract.php
This is a simple change that isn't really doing anything by itself, all it does is moving the merge of includes to the Serializer while keeping the current behavior. The point is to give serializers, especially those that side-load includes, a way to customize how includes are merged into the parent scope.
As an example; I was trying to write a EmberSerializer (based on #144), but since the IDs of the side-loaded relations aren't included in the parent scope there's no way for Ember to know which item the side-loaded data is related to. My custom serializer would, without this change, output something like this:
```json
{
"authors": [
{
"id": 1,
"name": "George R. R. Satan",
},
{
"id": 2,
"name": "Philip K Dick",
}
],
"books": [
{
"id": 1,
"name": "Game Of Kill Everyone"
},
{
"id": 2, …
```
=> Move merge of includes to Serializer

src/Resource/ResourceAbstract.php, src/Resource/ResourceInterface.php
The types of the getData and setData did not match. Since it seems a perfectly good use case to give for example a string in the setData, getData can also return other types.
For the collection it should only be able to set an array or arrayiIterator. Since no type checking is done throughout the code it makes no sense extending the setData method in Collection only to update its docblock.
=> Fixed incorrect returntype in docblock for getData method.

src/Resource/ResourceAbstract.php, test/Resource/CollectionTest.php
The `setMetaValue()` method has a complementary `getMetaValue()`, but `getMeta()` did not have a complementary `setMeta()` method.
This allows a set of meta data to be applied to the resource at once, preventing the need to do something like the following in application code.
```php
foreach ($someMetaData as $metaKey => $metaValue) {
$theResource->setMetaValue($metaKey, $metaValue);
}
```
I went with overwriting existing meta instead of merging because that's what `setMetaValue()` is doing for individual keys.
=> Add setMeta to ResourceAbstract

src/Manager.php
Just a little comment change: use | as modifier separator, instead of a comma.
=> Correcting modifier separator

src/Manager.php, src/Pagination/Cursor.php, src/Scope.php
=> Fix: Typos

src/Resource/Null.php, src/Resource/NullResource.php, src/Scope.php, src/Serializer/JsonApiSerializer.php, src/Serializer/SerializerAbstract.php, src/TransformerAbstract.php, test/Serializer/JsonApiSerializerTest.php, test/Stub/Transformer/JsonApiAuthorTransformer.php, test/Stub/Transformer/JsonApiBookTransformer.php
I am using fractal for my API responses, which is consumed by an Ember app and want to have a Serializer that converts to JSON API v1.0 (which will be the default in Ember's future).
I took a stab at the TODOs listed in #187:
> What we need to do:
>
> - [x] Add links
> - [x] Add relationships
>     - [x] to-one
>     - [x] to-many
>     - [x] nested relationships
>     - [x] empty relationships
> - [x] Always set data as resource key
> - [x] Rename includes to included
> - [x] Included resources should be moved outside the data object
> - [x] All resources should return id, type and attributes
Additional things to do:
I will try to add the remaining TODOs over this weekend.
Please provide feedback and mention any other things we need to get done before we can implement JSON APIs with …
=> Update `JsonApiSerializer` to be compatible with JSON API v1.0

test/ScopeTest.php
=> Fix: Also cover Scope::toJson()

src/Pagination/Cursor.php, src/ParamBag.php
=> Fix: Add missing arguments to docblocks

src/Scope.php
This PR
[x] removes `else`s and `elseif`s where we're returning early already
=> Fix: No need for else / elseif

test/Resource/ItemTest.php
This PR
:information_desk_person: Vertical whitespace helps - also, we're testing the behaviour of `League\Fractal\Resource\Item` here, right?
=> Fix: Clean up Item test

src/Scope.php, src/Serializer/JsonApiSerializer.php, src/Serializer/SerializerAbstract.php, test/Serializer/JsonApiSerializerTest.php
Additionally, this will fix any errors encountered when transforming objects instead of arrays. See [this comment](https://github.com/thephpleague/fractal/pull/205#issuecomment-136124723). 
Previously the serializer used the rawData (i.e. untransformed) to filter the root objects from the sideloads. Now it uses the transformed data, therefore it always is an array.
=> Fix inclusion of root objects into sideloaded array in JsonApiSerializer

.scrutinizer.yml, .travis.yml
This PR
:information_desk_person: This speeds up builds, and I believe (guess) that Scrutinizer only accepts the first submission for a build anyway (does it?), see https://scrutinizer-ci.com/docs/tools/external-code-coverage/.
=> Fix: Only collect and report coverage once

src/Manager.php, test/ManagerTest.php
Actually, with urls like  ````?include=comments:valid```` or ````?include=comments:valid()````, ````valid```` is not concern by parsing of params.
This PR allow it.
My real use case is in fact to have possibility to validate all kind of params (with or without options, and so valid or invalid) from my url whose I have access in my ParamBag
=> Allow param without values

test/ManagerTest.php, test/Pagination/CursorTest.php, test/Pagination/IlluminatePaginatorAdapterTest.php, test/Pagination/PagerfantaPaginatorAdapterTest.php, test/Pagination/ZendFrameworkPaginatorAdapterTest.php, test/ParamBagTest.php, test/Resource/CollectionTest.php, test/ScopeTest.php, test/Serializer/ArraySerializerTest.php, test/Serializer/DataArraySerializerTest.php, test/Serializer/JsonApiSerializerTest.php, test/TransformerAbstractTest.php
=> Fix: Assert sameness, not just equality

src/TransformerAbstract.php, test/Serializer/JsonApiSerializerTest.php, test/Stub/Transformer/JsonApiBookTransformer.php
For the JSON API specification recommends hyphens as separators for attribute and relationship names.
However the current version of Fractal only allows underscore and camelCase includes.
This fixes this by allowing includes to use `-` as separators as well for related models.
This includes a test with a new relationship for `co-author` on `JsonApiBookTransformer`.
=> Allows dasherized includes for JSONAPI Serializer

src/Serializer/JsonApiSerializer.php
Hi,
This PR changes the visibility of some methods of the JsonApiSerializer class, so that it's easier to extend from.
PS: Made a new PR to comply with the [rules](https://github.com/thephpleague/fractal/blob/master/CONTRIBUTING.md) (i.e. do not PR from `master` branch).
=> [RFC] Extending JSON API Serializer

src/Serializer/JsonApiSerializer.php
Retaining the key that the relationship has to the data it's included with, or if the relationship does not exist for that object then the relationship is pushed up when fillRelationships() is called
=> Fix issue including relationships on collections

transformers.md
1. Fix: Eager-Loading vrs Lazy-Loading referencing old example `$book->author`
2. Fix: Throw exception in multiple lines so you don't have to scroll horizontally 
3. Update example when ParamBag is null to explain https://github.com/thephpleague/fractal/issues/250 in docs
=> Update Transformer docs

transformers.md
A minor change, however, instead of “vrs”, it should probably be “vs”
to represent the shortened form of versus.
=> Change vrs to vs

transformers.md
“This above examples” sounds a little odd and might be a slight grammatical error. Perhaps “The above examples” would be more accurate.
=> Fix slight grammatical error

pagination.md
The docs for the cursor are a bit wonky and contain no examples at all. Updating the docs to be a bit more clear about what `previousCursor` should be containing and how the cursor should move.
=> Updating docs for pagination

src/Manager.php, src/Scope.php, src/TransformerAbstract.php, test/ManagerTest.php, test/ScopeTest.php, test/TransformerAbstractTest.php
Project requirements periodically mandate a nested Resource specified on a Transformer's `$defaultIncludes` property be omitted.
When a book should be accompanied by it's publisher during transformation to JSON the majority of the time, I have a `BookTransformer` like this.
```php
use League/Fractal/TransformerAbstract
class BookTransformer extends TransformerAbstract 
{
protected $defaultIncludes = [ 'publisher' ]; 
public function transform(Book $book)
{
// ...
}
public function includePublisher(Book $book)
{
// ...
}
}
```
For the times the publisher should be omitted, I have been subclassing the `BookTransformer`, resetting the `$defaultIncludes` property.
```php
use League/Fractal/TransformerAbstract
class BookTransformerWithoutPublisher extends TransformerAbstract 
{
protected …
```
=> Allow default / available, requested includes to be excluded

src/Resource/ResourceAbstract.php, src/Resource/ResourceInterface.php
Transformer could be a `callable` or `TransformerAbstract`. Scrutinizer static analysis of projects using Fractal have false issues for client classes creating Resources with their associated Transformer as these are not `callable` nor `string`
=> Fixup some type hintings related to Resource

src/Manager.php, src/TransformerAbstract.php
Having to check whether there is a ParamBag or not is error prone.
This PR ensures Transformers are always called with a `ParamBag` instance.
=> Always returns a ParamBag

src/Scope.php, src/Serializer/ArraySerializerWithNull.php, test/ScopeTest.php, test/Stub/ArraySerializerWithNull.php, test/Stub/Transformer/NullIncludeBookTransformer.php
This fix is needed in case of returning NullResource and return null.
In case of meta is not empty we will return meta array
=> Fix when nullResource returned from Transformers

src/Serializer/JsonApiSerializer.php
One of the things making this class difficult to maintain is that there is a lot of nested looping so it gets difficult to see what is actually happening.
I noticed that in Scrutinizer CI it was shouting about this in particular so I pulled it out into a method and returned it. I was tempted to pass the `$linkedIds` by reference as it is used by the loop and not returned, however I think that doing so would have made it more difficult to understand (Even though my implementation uses `list` to achieve a similar functionality)
There's also a question about masking the loops here, as from just reading the code you don't know that the method is going to loop through an array of data, although just reading through the code should be enough to do so. I could rename the method …
=> pulled duplicated code out into a private method

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php
=> Enhancement: allow the ability to define meta on each object in collection

src/Scope.php, test/ScopeTest.php
Adds flexibility passing (optionally) an `$options` parameter to `toJson` method.
E.g. You could use this for debugging: `$this->fractal->createData($resource)->toJson(JSON_PRETTY_PRINT);`
=> Add $options parameter to toJson

test/ManagerTest.php, test/ParamBagTest.php, test/Resource/CollectionTest.php, test/Resource/ItemTest.php, test/ScopeTest.php, test/Serializer/JsonApiSerializerTest.php, test/TransformerAbstractTest.php
This PR
🤷‍♂️ PhpStorm complains otherwise.
=> Fix: Reference classes in annotations relative to root namespace

test/Resource/CollectionTest.php, test/Resource/ItemTest.php, test/Serializer/ArraySerializerTest.php, test/Serializer/DataArraySerializerTest.php, test/Serializer/JsonApiSerializerTest.php
=> Fix: Class name does not match project structure

src/Resource/Primitive.php, src/Scope.php, src/TransformerAbstract.php, test/Resource/PrimitiveTest.php, test/ScopeTest.php, test/Stub/Transformer/PrimitiveIncludeBookTransformer.php
Added `Primitive` resource type, allows to use primitives (strings, ints, floats) to be included, just like arrays.
This will allow to optionally include primitive fields in the transformed data. Currently, only `Item`s and `Collection`s can be included in the transformed data.
Example : 
```php
<?php 
use Book;
class MyTransformer extends TransformerAbstract
{
$availableIncludes = ['price'];
public function includePrice(Book $book)
{
return $this->primitive($book->price, function ($price) {
return $price + 40; // This can get complex
});
}
}
?>
```
=> [Feature] Add 'Primitive' Resource

src/Manager.php, src/ScopeFactory.php, src/ScopeFactoryInterface.php, test/ScopeFactoryTest.php
I have a use case where I wish to profile serialization. I want to log all calls to transformers. To do this, I need to inject my logging scopes.
This PR introduces a scope factory interface to properly generate configured scope instances. When not injected, a default factory is created which has the same behavior as current `Manager::createData` implementation.
=> Introduce Scope Factory

src/Serializer/ArraySerializer.php
If paginator has no links it returns empty JSON array, but when it is not empty it returns object. It will be better if an object will be returned, even empty.
=> convert links array to object if empty in ArraySerializer

src/Manager.php, test/ManagerTest.php
Hi. The `parseFieldsets` method of the Manager expects an array with strings, for then to parse it to an array. This PR adds a failing test and code satisfying the test allowing array of arrays to be passed directly.
=> Allow array lists to parseFieldsets

.travis.yml
Travis errors on hhvm builds with:
```
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
```
So let's `dist: trusty`
=> Update travis config to use trusty for hhvm

_layouts/default.html
site is broken over https, such as when using https://www.eff.org/https-everywhere
=> fix mixed content errors over https

src/Scope.php, test/ScopeTest.php
Use array union (`+` operator) instead of `array_merge` so that numeric keys within data are preserved.
Example: previously Fractal would convert
```
[
'1' => 'First',
'2' => 'Second',
'5' => 'Fifth',
'non-numeric' => 'Test',
]
```
to 
```
[
'0' => 'First',
'1' => 'Second',
'2' => 'Fifth',
'non-numeric' => 'Test',
]
```
Now the keys are preserved correctly.
=> Preserve numeric keys in arrays

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php
• Reference Issue #420 
• Allow provided self link to overwrite default generated self link
• Provide test for this merge case: testCustomSelfLinkMerge()
• Alter expected results for testCustomLinkMerge() due to change in array_merge parameter order
=> Properly merge self link for JsonApiSerializer

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php, test/Stub/Transformer/JsonApiEmptyTransformer.php
If you transform a resource without any attributes using the JsonApiSerializer the resulting JSON currently looks like `"attributes": []`. This does not satisfy the JSON API spec: [The value of the attributes key MUST be an object (an “attributes object”).](http://jsonapi.org/format/#document-resource-object-attributes).
It would also be possible to remove the entire attributes key from the resource object, since JSON API does not require it. However, I think many clients expect there to be an attributes key, so it is better to set it to an empty object. It just can't be an array.
If you would like me to make any changes to the pull request, don't hesitate to ask.
=> Convert attributes to empty object if there are no attributes

src/Pagination/PhalconFrameworkPaginatorAdapter.php, test/Pagination/PhalconFrameworkPaginatorAdapterTest.php
The Phalcon paginator used to accept a paginator object and in the constructor would use the `getPaginate()` method which executes a database query. The same method was used prior to invoking the paginator to set up the `Collection` object. 
Therefore the Phalcon paginator was executing two queries instead of just one, thus rendering caching techniques useless.
This PR solves this issue by altering the paginator to accept the `stdClass` object that the Phalcon paginator returns.
=> Performance improvement for Phalcon Paginator

.travis.yml
HHVM is failing due to an issue with composer. Let's just ignore HHVM failures for now and decide what to do with it later.
=> Allow HHVM to fail so that tests can complete

composer.json, phpunit.xml.dist, test/ScopeFactoryTest.php, test/TransformerAbstractTest.php
This allows the `0.x` series of Fractal to have passing tests without errors on PHP 5.4 all the way up to PHP 7.3.
I added an allowance for using the PHPUnit 7 series on versions of PHP that support it, and I made a few slight changes to tests and `phpunit.xml.dist` that allow the tests to continue running on both the older version of PHPUnit and the newer versions.
FYI, when you choose to upgrade to PHPUnit 8.x for the `1.x` series of this library, you'll need to make more changes to the tests that won't be backwards compatible with earlier versions of PHPUnit.
=> Allow use of newer PHPUnit on newer versions of PHP

src/Scope.php, src/Serializer/JsonApiSerializer.php, src/Serializer/SerializerAbstract.php, test/Serializer/JsonApiSerializerTest.php
This PR changes the JsonApiSerializer to always add a 'relationships' key with links.  Before the serializer would only add links if the resource was included.
I had to update a lot of tests since the output changes.  This is a breaking change since new data is added to the output, but nothing is removed from the output so it shouldn't actually break any clients.
Closes #292 & #242.  Supersedes the changes in #272, so that PR should not be merged if this one is.
[Here is a link to the relevant part of the JSON:API specification](http://jsonapi.org/format/#document-resource-object-relationships).
=> Add links for all available includes to JsonApiSerializer

CHANGELOG.md, src/Scope.php, test/ScopeTest.php
So the idea here may have already been a thing...but I'd like to propose implementing \JsonSerializable on Scopes.
It saves a call to `toArray()` and would allow for Scopes to be passed directly to `json_encode()`
This saves a little time depending on how mocky / stubby your tests get in your consumer implementation as there is one less message to pass through with whatever value you're interested in returning / asserting against. 
So in our codebase (and I assume some others) our controller or responder might look like
```php
$this->respond($this->manager->createData($resource)->toArray());
// OR
$this->respond($this->manager->createData($resource));
// to test with mocks we have to mock a Scope and stub `toArray()` and assert on that
// or we could just assert that the responder method …
```
=> Implement \JsonSerializable for Scopes

src/Pagination/Cursor.php
Change typehints in the phpDoc for the setters to match CursorInterface types.
=> Fix phpDoc param typehint for setters in Cursor class

src/Manager.php, test/ManagerTest.php
With this feature, "include" will be available like this ?include=foo:limit(10|1).bar,baz
Response example:
```json
{
"data": {
"name": "lorem",
"foo": {
"data": [
{"name": "ipsum", "bar": {"data": {"name": "dolor"}}},
{"name": "ipsum", "bar": {"data": {"name": "dolor"}}}
],
"meta": {
"pagination": {}
}
},
"baz": {}
}
}
```
=> Allow sub relations with modifier

.travis.yml
php 5.4 and 5.5 are long dead however there is a chance some people are still using it in production. We don't really want to worry about it, so we will let Travis allow these failures on code checks.
=> update travis to allow failures on 54 and 55

.travis.yml
We should have tests required for PHP 5.4 and 5.5 as they are officially supported versions. I'm using this PR to get them working.
=> Fix tests for PHP 5.4 and 5.5

src/Manager.php, src/ParamBag.php, src/Scope.php
This fixes the following error on PHP 8.1 RC6:
```
Fatal error: During inheritance of JsonSerializable: Uncaught ErrorException: Return type of League\Fractal\Scope::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/league/fractal/src/Scope.php:298
```
Related to #526
=> Add support for PHP 8.1

README.md
The supported versions in the readme are outdated after the `0.20` release.
=> Update supported versions in the readme

transformers.md
1) Return type was wrong
2) When no parameters were given, comments weren't transformed.
Let me know if you need empty new lines added in the second commit, I'm always happy to edit my branch history.
---
https://github.com/thephpleague/fractal/blob/9c9c493edcf0f5438555e5b515a790749a26c807/src/TransformerAbstract.php#L279-L291
=> [gh-pages] Correct two overlooks in transformer's collection example

README.md
I'm sorry, it seems like markdown doesn't like `>` symbols :disappointed: 
Fixes #546
=> Fix supported version in the readme

composer.json
so this way people can run these tools locally, before they hit CI.
=> Add static analysis

src/Scope.php, src/Serializer/ArraySerializer.php, src/Serializer/DataArraySerializer.php, src/Serializer/JsonApiSerializer.php, src/Serializer/Serializer.php, test/Serializer/CustomArraySerializerTest.php, test/Serializer/DataArraySerializerTest.php, test/Stub/Serializer/RootSerializer.php, test/Stub/Transformer/GenericBookNoResourceKeyTransformer.php
=> allow for null values to be passed to Scope

src/TransformerAbstract.php, test/TransformerAbstractTest.php
This change adds an explicit default value to the `$currentScope` property of `TransformerAbstract` since it's not hydrated in the constructor.
- See psalm `MissingConstructor` issue: https://psalm.dev/r/639278ed1b (in reality, this can also flag a `PropertyNotSetInConstructor` issue)
- and 3v4l demonstrating the problem: https://3v4l.org/j5oVI#v7.4.28
I'd suggest this as a patch release, I can't see how this might break any existing functionality.
=> Explicitly default TransformerAbstract::currentScope to null since it's not defined in the constructor

.github/workflows/run-tests.yml, .github/workflows/static.yml, .gitignore, composer.json, phpstan.neon.dist, psalm.xml, src/Manager.php, src/Pagination/DoctrinePaginatorAdapter.php, src/Pagination/LaminasPaginatorAdapter.php, src/Pagination/PagerfantaPaginatorAdapter.php, src/Pagination/PaginatorCountTrait.php, src/Pagination/TraversableCountTrait.php, test/Pagination/DoctrinePaginatorAdapterTest.php, test/Pagination/LaminasFrameworkPaginatorAdapterTest.php, test/Pagination/PaginatorCountTraitTest.php, test/Serializer/DataArraySerializerTest.php, test/Stub/SimpleTraversable.php, test/phpstan.php
This PR fixes deprecated errors and resolved #574 by:
1. Updating typed arguments that have `= null` but don't have a nullable type
2. Allowing newer versions of Pagerfanta in dev dependencies.
3. Switching from Zend to Laminas in tests, which is fully compatible. In doing so I also duplicated the Zend paginator adapter for use with Laminas
This PR builds on the changes from #572
=> Fix deprecated errors in tests
