thephpleague/fractal

pagination.md
Just a few fixes to the paginator docs, updating the list of adapters, reformatting the Laravel example and making a few formatting and grammatical fixes.
=> Paginator fixes

src/TransformerAbstract.php
This updates the function names referenced the TransformerAbstract class docblock.
=> Update function names in docblock

installation.md
(best to only merge this in when next version is tagged, which actually has 5.4 as min req.)
=> PHP Min version in docs

.travis.yml
- PHPUnit does not support PHP 7 codecoverage
=> Fix: Fixes scrutinizer

pagination.md
Use the `appends()` method on the paginator instance in favour of `addQuery()` with a foreach loop. Makes the example look a bit cleaner :)
Thanks for the awesome package!
=> Change use of addQuery() to appends()

serializers.md
=> Update documentation of JsonApiSerializer

src/ParamBag.php
=> Add IteratorAggregate implementation to ParamBag

src/Scope.php, test/ScopeTest.php
=> Add Resource getter in Scope

transformers.md
Add example of params validation
=> [DOC] Params validation example

.travis.yml
=> Enhancement: Send builds to container-based infrastructure

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php
Adds pagination as in example on http://jsonapi.org/examples/#pagination and according to specification on http://jsonapi.org/format/#fetching-pagination
=> Adds pagination to JsonApiSerializer

src/Scope.php, test/ScopeTest.php
- Added line to set the scope in the transformer before running the transform function
=> Scope is not set in the transformer

src/Serializer/JsonApiSerializer.php
Fixed unused variables and added docblocks
=> Remove unused variables

src/Resource/ResourceInterface.php, src/Serializer/ArraySerializer.php, src/Serializer/DataArraySerializer.php, src/Serializer/SerializerAbstract.php, test/Serializer/ArraySerializerTest.php, test/Serializer/DataArraySerializerTest.php
Fixes issue https://github.com/thephpleague/fractal/issues/278
=> Adds missing methods for serializing null resource.

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php
- Divided the methods into smaller chunks for better readability.
=> Refactored the JsonApiSerializer

transformers.md
=> Documenting Manager::parseExcludes()

src/Resource/ResourceAbstract.php, src/TransformerAbstract.php
Simple PSR2 spacing error fixes
=> Fix minor PSR2 errors

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php
**This "fixes":** Links that are specified in the link part in a transformer should be merge. 
from https://github.com/thephpleague/fractal/issues/264
=> merge custom links in serializer

src/Serializer/JsonApiSerializer.php
- Fixed an inconsistent method name.
=> Fixed an inconsistent method name

resources.md
Hi 
JSON-API dont tell about it: http://jsonapi.org/format/#document-links
=> Remove a rel attribute

src/Resource/Collection.php, src/Resource/Item.php
=> Fixed typo in documentation

src/Serializer/Serializer.php, src/Serializer/SerializerAbstract.php
I have added a new Serializer interface for the serializers to allow dependencies to be set on this interface instead of a concrete implementation.
The interface has all the same methods that the SerializerAbstract has.
=> Serializer interface

index.md
=> fix link to license file

composer.json, test/ManagerTest.php, test/Pagination/CursorTest.php, test/Pagination/DoctrinePaginatorAdapterTest.php, test/Pagination/IlluminatePaginatorAdapterTest.php, test/Pagination/PagerfantaPaginatorAdapterTest.php, test/Pagination/PhalconFrameworkPaginatorAdapterTest.php, test/Pagination/ZendFrameworkPaginatorAdapterTest.php, test/ParamBagTest.php, test/Resource/CollectionTest.php, test/Resource/ItemTest.php, test/Resource/PrimitiveTest.php, test/ScopeFactoryTest.php, test/ScopeTest.php, test/Serializer/ArraySerializerTest.php, test/Serializer/DataArraySerializerTest.php, test/Serializer/JsonApiSerializerTest.php, test/TransformerAbstractTest.php
This PR resolves:
* tests now extend from namespaced TestCase
=> Use namespaced TestCase

src/Serializer/JsonApiSerializer.php, test/Serializer/JsonApiSerializerTest.php, test/Stub/Transformer/JsonApiBookTransformer.php
This patch will make setMeta on include relationship work
=> Include meta key in relationships

pagination.md
As suggested by #437 I have added a basic example for Symfony
=> Adding Symfony pagination example

pagination.md
Minor corrections to the documentation
Added example for the Phalcon paginator.
=> Added example for Phalcon pagination

CHANGELOG.md
I've added the last two releases to the changelog
=> Add 0.17.0+ to the changelog

README.md
I did this in alphabetical order :D
=> Add maintainers to the readme

.github/workflows/run-tests.yml
=> Run tests on PHP 8.1

.github/workflows/run-tests.yml
Highly opinionated, but this make the CI file easier to read.
=> Clean up CI

.editorconfig, .github/workflows/.editorconfig
This help contributros to style their changes correctly.
=> Added .editorconfig

.github/workflows/static.yml, phpstan-baseline.neon, phpstan.neon.dist, psalm.baseline.xml, psalm.xml
I'll do a first run then find the errors
=> Adding phpstan and psalm
